AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Claude Code Activity Dashboard - Lambda Ingest Function

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Environment:
      Variables:
        SNOWFLAKE_ACCOUNT: '{{resolve:secretsmanager:claude-code-dashboard:SecretString:snowflake_account}}'
        SNOWFLAKE_USER: '{{resolve:secretsmanager:claude-code-dashboard:SecretString:snowflake_user}}'
        SNOWFLAKE_PASSWORD: '{{resolve:secretsmanager:claude-code-dashboard:SecretString:snowflake_password}}'
        SNOWFLAKE_DATABASE: '{{resolve:secretsmanager:claude-code-dashboard:SecretString:snowflake_database}}'
        SNOWFLAKE_WAREHOUSE: '{{resolve:secretsmanager:claude-code-dashboard:SecretString:snowflake_warehouse}}'
        API_KEY: '{{resolve:secretsmanager:claude-code-dashboard:SecretString:api_key}}'

Resources:
  ClaudeCodeIngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      CodeUri: ./
      Events:
        PostEvent:
          Type: HttpApi
          Properties:
            Path: /events
            Method: POST
            ApiId: !Ref HttpApi

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - POST
        AllowHeaders:
          - Content-Type
          - x-api-key

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/events'
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ClaudeCodeIngestFunction.Arn
